//! TypeScript generation entrypoint for the npm `./shared` surface.
//!
//! Runs only under the `ts-export` feature. It drives `ts-rs` to emit the data-type
//! declarations and then hand-codegens the constant files `ts-rs` cannot express
//! (cookie defaults, the route table, the `AUTH_ERROR_CODES` map) plus a barrel
//! `index.ts`. All output lands in `packages/rust-auth/src/shared/`.
//!
//! # Staleness gate
//!
//! ```text
//! cargo test -p bymax-auth-types --features ts-export
//! git diff --exit-code -- packages/rust-auth/src/shared
//! ```
//!
//! CI runs exactly this: a non-empty diff means the committed TypeScript drifted from
//! the Rust contract and the build fails.
#![cfg(feature = "ts-export")]

use std::fs;
use std::path::{Path, PathBuf};

use bymax_auth_types::constants::{
    AUTH_ACCESS_COOKIE_NAME, AUTH_HAS_SESSION_COOKIE_NAME, AUTH_HAS_SESSION_COOKIE_VALUE,
    AUTH_REFRESH_COOKIE_NAME, AUTH_REFRESH_COOKIE_PATH, AUTH_ROUTE_PREFIX,
    MFA_TEMP_COOKIE_MAX_AGE_SECONDS, MFA_TEMP_COOKIE_NAME, routes,
};
use bymax_auth_types::error::AuthErrorCode;
use bymax_auth_types::{
    AuthErrorResponse, AuthResult, DashboardClaims, FieldError, LoginResult, MfaChallengeResult,
    MfaTempClaims, PlatformAuthResult, PlatformClaims, PlatformLoginResult, RotatedTokens,
    SafeAuthPlatformUser, SafeAuthUser,
};
use ts_rs::TS;

/// Banner stamped on every hand-codegen file so a reader knows not to edit it.
const BANNER: &str = "// GENERATED by bymax-auth-types ts-rs — do not edit by hand.";

/// Aggregator whose dependency closure is every cross-boundary type. Exporting it in a
/// single `export_all_to` call writes all the grouped `.ts` files at once, so types
/// that share a file (e.g. both `Safe*` projections) land together without one call
/// clobbering another's output.
///
/// The fields exist only to anchor each type in `ts-rs`'s export traversal (which
/// follows field *types*, not names); they are never read, so each is `_`-prefixed to
/// signal intentional non-use without a lint suppression.
#[derive(TS)]
#[ts(export_to = "_export_root.ts")]
struct ExportRoot {
    _safe_user: SafeAuthUser,
    _safe_platform_user: SafeAuthPlatformUser,
    _dashboard: DashboardClaims,
    _platform: PlatformClaims,
    _mfa_temp: MfaTempClaims,
    _auth_result: AuthResult,
    _platform_result: PlatformAuthResult,
    _mfa_challenge: MfaChallengeResult,
    _login: LoginResult,
    _platform_login: PlatformLoginResult,
    _rotated: RotatedTokens,
    _error_response: AuthErrorResponse,
    _field_error: FieldError,
    _error_code: AuthErrorCode,
}

/// Absolute path to the npm package's generated `./shared` directory.
fn shared_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../../packages/rust-auth/src/shared")
}

/// Every catalog code, in a fixed order, so the generated map is deterministic.
fn all_error_codes() -> [AuthErrorCode; 38] {
    use AuthErrorCode::*;
    [
        InvalidCredentials,
        AccountLocked,
        AccountInactive,
        AccountSuspended,
        AccountBanned,
        PendingApproval,
        TokenExpired,
        TokenRevoked,
        TokenInvalid,
        RefreshTokenInvalid,
        SessionExpired,
        SessionLimitReached,
        SessionNotFound,
        TokenMissing,
        EmailAlreadyExists,
        EmailNotVerified,
        MfaRequired,
        MfaInvalidCode,
        MfaAlreadyEnabled,
        MfaNotEnabled,
        MfaSetupRequired,
        MfaTempTokenInvalid,
        RecoveryCodeInvalid,
        PasswordTooWeak,
        PasswordResetTokenInvalid,
        PasswordResetTokenExpired,
        OtpInvalid,
        OtpExpired,
        OtpMaxAttempts,
        InsufficientRole,
        Forbidden,
        InvalidInvitationToken,
        OauthFailed,
        OauthEmailMismatch,
        PlatformAuthRequired,
        Validation,
        TooManyRequests,
        Internal,
    ]
}

/// The `auth.*` wire string for a code (via serde), with the JSON quotes trimmed.
fn code_string(code: AuthErrorCode) -> String {
    serde_json::to_string(&code)
        .unwrap_or_default()
        .trim_matches('"')
        .to_owned()
}

/// The SCREAMING_SNAKE_CASE map key for a code: `auth.invalid_credentials` →
/// `INVALID_CREDENTIALS`.
fn code_key(wire: &str) -> String {
    wire.strip_prefix("auth.").unwrap_or(wire).to_uppercase()
}

/// Write `body` (prefixed with the generated banner) to `shared/<name>`.
fn write_shared(name: &str, body: &str) {
    let path = shared_dir().join(name);
    let contents = format!("{BANNER}\n\n{body}");
    let result = fs::write(&path, contents);
    assert!(result.is_ok(), "failed to write {name}: {result:?}");
}

/// Emit `cookie-defaults.ts` from the Rust constants, so the names cannot drift.
fn write_cookie_defaults() {
    let body = format!(
        "export const AUTH_ACCESS_COOKIE_NAME = {AUTH_ACCESS_COOKIE_NAME:?};\n\
         export const AUTH_REFRESH_COOKIE_NAME = {AUTH_REFRESH_COOKIE_NAME:?};\n\
         export const AUTH_HAS_SESSION_COOKIE_NAME = {AUTH_HAS_SESSION_COOKIE_NAME:?};\n\
         export const AUTH_HAS_SESSION_COOKIE_VALUE = {AUTH_HAS_SESSION_COOKIE_VALUE:?};\n\
         export const AUTH_REFRESH_COOKIE_PATH = {AUTH_REFRESH_COOKIE_PATH:?};\n\
         export const MFA_TEMP_COOKIE_NAME = {MFA_TEMP_COOKIE_NAME:?};\n\
         export const MFA_TEMP_COOKIE_MAX_AGE_SECONDS = {MFA_TEMP_COOKIE_MAX_AGE_SECONDS};\n",
    );
    write_shared("cookie-defaults.ts", &body);
}

/// Emit `routes.ts` — the default route table as a frozen `AUTH_ROUTES` object.
fn write_routes() {
    let entries = [
        ("REGISTER", routes::AUTH_REGISTER),
        ("LOGIN", routes::AUTH_LOGIN),
        ("LOGOUT", routes::AUTH_LOGOUT),
        ("REFRESH", routes::AUTH_REFRESH),
        ("ME", routes::AUTH_ME),
        ("VERIFY_EMAIL", routes::AUTH_VERIFY_EMAIL),
        ("RESEND_VERIFICATION", routes::AUTH_RESEND_VERIFICATION),
        ("WS_TICKET", routes::AUTH_WS_TICKET),
        ("MFA_SETUP", routes::MFA_SETUP),
        ("MFA_VERIFY_ENABLE", routes::MFA_VERIFY_ENABLE),
        ("MFA_CHALLENGE", routes::MFA_CHALLENGE),
        ("MFA_DISABLE", routes::MFA_DISABLE),
        ("MFA_RECOVERY_CODES", routes::MFA_RECOVERY_CODES),
        ("PASSWORD_FORGOT", routes::PASSWORD_FORGOT),
        ("PASSWORD_RESET", routes::PASSWORD_RESET),
        ("PASSWORD_VERIFY_OTP", routes::PASSWORD_VERIFY_OTP),
        ("PASSWORD_RESEND_OTP", routes::PASSWORD_RESEND_OTP),
        ("SESSIONS_LIST", routes::SESSIONS_LIST),
        ("SESSIONS_REVOKE_ALL", routes::SESSIONS_REVOKE_ALL),
        ("SESSIONS_REVOKE_ONE", routes::SESSIONS_REVOKE_ONE),
        ("PLATFORM_LOGIN", routes::PLATFORM_LOGIN),
        ("PLATFORM_MFA_CHALLENGE", routes::PLATFORM_MFA_CHALLENGE),
        ("PLATFORM_ME", routes::PLATFORM_ME),
        ("PLATFORM_LOGOUT", routes::PLATFORM_LOGOUT),
        ("PLATFORM_REFRESH", routes::PLATFORM_REFRESH),
        (
            "PLATFORM_SESSIONS_REVOKE_ALL",
            routes::PLATFORM_SESSIONS_REVOKE_ALL,
        ),
        ("PLATFORM_MFA_SETUP", routes::PLATFORM_MFA_SETUP),
        (
            "PLATFORM_MFA_VERIFY_ENABLE",
            routes::PLATFORM_MFA_VERIFY_ENABLE,
        ),
        ("PLATFORM_MFA_DISABLE", routes::PLATFORM_MFA_DISABLE),
        (
            "PLATFORM_MFA_RECOVERY_CODES",
            routes::PLATFORM_MFA_RECOVERY_CODES,
        ),
        ("OAUTH_INITIATE", routes::OAUTH_INITIATE),
        ("OAUTH_CALLBACK", routes::OAUTH_CALLBACK),
        ("INVITATIONS_CREATE", routes::INVITATIONS_CREATE),
        ("INVITATIONS_ACCEPT", routes::INVITATIONS_ACCEPT),
    ];
    let mut body = format!("export const AUTH_ROUTE_PREFIX = {AUTH_ROUTE_PREFIX:?};\n\n");
    body.push_str("export const AUTH_ROUTES = {\n");
    for (key, path) in entries {
        body.push_str(&format!("  {key}: {path:?},\n"));
    }
    body.push_str("} as const;\n");
    write_shared("routes.ts", &body);
}

/// Append the `AUTH_ERROR_CODES` map to the ts-rs-generated `error-codes.ts` (which
/// already holds the `AuthErrorCode` union). The append runs after ts-rs writes the
/// file, so a regeneration reproduces byte-identical output.
fn append_error_code_map() {
    let path = shared_dir().join("error-codes.ts");
    let union = fs::read_to_string(&path).unwrap_or_default();
    let mut body = String::from("\nexport const AUTH_ERROR_CODES = {\n");
    for code in all_error_codes() {
        let wire = code_string(code);
        body.push_str(&format!("  {}: {:?},\n", code_key(&wire), wire));
    }
    body.push_str("} as const;\n");
    let result = fs::write(&path, format!("{}{}", union.trim_end(), body));
    assert!(
        result.is_ok(),
        "failed to append AUTH_ERROR_CODES: {result:?}"
    );
}

/// Emit the barrel `index.ts` re-exporting every generated module plus the small
/// hand-written runtime set (`AuthClientError`/`AuthResponseCode` and the refresh-skip
/// builder). The hand-written modules are not produced by `ts-rs`, but the barrel ties
/// the whole `./shared` surface together, so it lists them here; the generator never
/// overwrites those source files, so the staleness gate stays clean.
fn write_index() {
    let modules = [
        "auth-user.types",
        "jwt-payload.types",
        "auth-result.types",
        "auth-error.types",
        "error-codes",
        "cookie-defaults",
        "routes",
        // Hand-written runtime helpers (see the files of the same name).
        "auth-client-error",
        "refresh-skip",
    ];
    let mut body = String::new();
    for module in modules {
        body.push_str(&format!("export * from \"./{module}\";\n"));
    }
    write_shared("index.ts", &body);
}

#[test]
fn generates_the_shared_typescript_surface() {
    // Drive ts-rs for every cross-boundary type in one call (so shared files merge),
    // then hand-codegen the constant files and the barrel. Re-running this is the
    // staleness gate: a clean tree after regeneration proves the committed TS is
    // in sync with the Rust contract.
    let dir = shared_dir();
    let exported = ExportRoot::export_all_to(&dir);
    assert!(exported.is_ok(), "ts-rs export failed: {exported:?}");

    // The aggregator's own marker file is an artifact of the single-call trick.
    // Best-effort cleanup: a `NotFound` (already absent) is the desired end state, so the
    // result is intentionally discarded rather than propagated.
    let _ = fs::remove_file(dir.join("_export_root.ts"));

    append_error_code_map();
    write_cookie_defaults();
    write_routes();
    write_index();

    // Sanity: the key generated files exist and carry real content.
    for name in [
        "auth-user.types.ts",
        "jwt-payload.types.ts",
        "auth-result.types.ts",
        "auth-error.types.ts",
        "error-codes.ts",
        "cookie-defaults.ts",
        "routes.ts",
        "index.ts",
    ] {
        let path = dir.join(name);
        let contents = fs::read_to_string(&path).unwrap_or_default();
        assert!(!contents.is_empty(), "generated file is empty: {name}");
    }

    // The generated payload type carries the nest-auth TS name and the `type`
    // discriminator field, proving the rename + serde-compat wiring reached the output.
    let jwt = fs::read_to_string(dir.join("jwt-payload.types.ts")).unwrap_or_default();
    assert!(jwt.contains("DashboardJwtPayload"));
    assert!(jwt.contains("mfaEnabled"));

    // The error-code surface carries both the union and the constant map.
    let codes = fs::read_to_string(dir.join("error-codes.ts")).unwrap_or_default();
    assert!(codes.contains("auth.invalid_credentials"));
    assert!(codes.contains("AUTH_ERROR_CODES"));
    assert!(codes.contains("INVALID_CREDENTIALS"));
}
