//! The OAuth provider contract. Each provider implements [`OAuthProvider`]: build the
//! authorization URL (with CSRF `state` and optional PKCE challenge), exchange the
//! authorization code, and fetch a normalized profile. All provider network I/O goes
//! through the injected [`crate::traits::HttpClient`], so the `oauth` feature carries no
//! transport dependency of its own.

use std::sync::Arc;

use async_trait::async_trait;

/// A pluggable OAuth provider, held on the engine and resolved by [`OAuthProvider::name`].
///
/// # Errors
///
/// [`OAuthProvider::exchange_code`] and [`OAuthProvider::fetch_profile`] return
/// [`OAuthProviderError`]; the engine maps every variant to the opaque client-facing
/// `OAuthFailed`, never leaking provider internals to callers.
#[async_trait]
pub trait OAuthProvider: Send + Sync {
    /// Stable provider identifier, used as the `{provider}` route segment and the
    /// storage/lookup key (e.g. `"google"`). Must match `^[a-z0-9-]{1,64}$`.
    fn name(&self) -> &str;

    /// Build the provider authorization URL.
    ///
    /// - `state`: the 64-hex CSRF nonce generated by the engine and validated on callback.
    /// - `code_challenge`: an optional PKCE S256 challenge (RFC 7636); when `Some`, the
    ///   URL includes `code_challenge` and `code_challenge_method=S256`.
    fn authorize_url(&self, state: &str, code_challenge: Option<&str>) -> String;

    /// Exchange the authorization `code` for provider tokens, forwarding the optional
    /// PKCE `code_verifier` when the flow was initiated with PKCE.
    async fn exchange_code(
        &self,
        code: &str,
        code_verifier: Option<&str>,
    ) -> Result<OAuthTokens, OAuthProviderError>;

    /// Fetch and normalize the user's profile using the provider `access_token`.
    async fn fetch_profile(&self, access_token: &str) -> Result<OAuthProfile, OAuthProviderError>;
}

/// A provider token-endpoint response. `access_token` is the only field the engine
/// requires; the rest are retained for providers/observability. The `Debug` impl redacts
/// the three credential fields so they can never leak into a log.
#[derive(Clone)]
pub struct OAuthTokens {
    /// The provider access token.
    pub access_token: String,
    /// The token type (asserted to be bearer before the access token is used).
    pub token_type: String,
    /// Optional access-token lifetime in seconds.
    pub expires_in: Option<u64>,
    /// Optional granted scope string.
    pub scope: Option<String>,
    /// Optional OpenID Connect id token.
    pub id_token: Option<String>,
    /// Optional refresh token.
    pub refresh_token: Option<String>,
}

impl std::fmt::Debug for OAuthTokens {
    /// Redacts `access_token`, `id_token`, and `refresh_token` — the credential fields —
    /// so a `{:?}` of provider tokens never exposes a usable secret.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("OAuthTokens")
            .field("access_token", &"[REDACTED]")
            .field("token_type", &self.token_type)
            .field("expires_in", &self.expires_in)
            .field("scope", &self.scope)
            .field("id_token", &self.id_token.as_ref().map(|_| "[REDACTED]"))
            .field(
                "refresh_token",
                &self.refresh_token.as_ref().map(|_| "[REDACTED]"),
            )
            .finish()
    }
}

/// A normalized identity returned by every provider. Shape matches the nest-auth
/// `OAuthProfile`.
#[derive(Clone, Debug)]
pub struct OAuthProfile {
    /// The provider name (e.g. `"google"`).
    pub provider: String,
    /// The opaque, stable user id within the provider.
    pub provider_id: String,
    /// The verified email address.
    pub email: String,
    /// Display name; providers that omit it leave `None`, and the engine derives a
    /// fallback from the email local-part on account creation.
    pub name: Option<String>,
    /// Optional avatar URL.
    pub avatar: Option<String>,
}

/// A provider-layer transport/validation error. The engine maps every variant to the
/// client-facing `OAuthFailed`, while logging the cause for monitoring.
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum OAuthProviderError {
    /// The provider returned a non-2xx HTTP status. Carried as a `u16` so the contract
    /// stays free of any external `StatusCode` type (parity with [`crate::traits::HttpResponse`]).
    #[error("oauth provider returned http status {0}")]
    Http(u16),
    /// A transport-layer failure reaching the provider.
    #[error("oauth provider transport error: {0}")]
    Transport(String),
    /// The token endpoint returned a non-bearer `token_type`.
    #[error("oauth provider returned unexpected token type: {0}")]
    UnexpectedTokenType(String),
    /// The provider did not positively confirm the email as verified.
    #[error("oauth provider email is not verified")]
    EmailNotVerified,
    /// A response body could not be decoded into the expected shape.
    #[error("oauth provider response decode error: {0}")]
    Decode(String),
}

/// The provider registry built from the consumer's OAuth config and held by the engine.
/// A thin newtype over the provider list so a single value carries every registered
/// provider into the builder.
#[derive(Clone, Default)]
pub struct OAuthProviders(pub Vec<Arc<dyn OAuthProvider>>);

impl OAuthProviders {
    /// Construct an empty registry.
    #[must_use]
    pub fn new() -> Self {
        Self(Vec::new())
    }

    /// Append a provider to the registry.
    #[must_use]
    pub fn with(mut self, provider: Arc<dyn OAuthProvider>) -> Self {
        self.0.push(provider);
        self
    }

    /// Whether the registry holds no providers.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A trivial provider proving [`OAuthProvider`] is object-safe and its value types
    /// round-trip through the trait object.
    struct DummyProvider;

    #[async_trait]
    impl OAuthProvider for DummyProvider {
        fn name(&self) -> &str {
            "dummy"
        }
        fn authorize_url(&self, state: &str, code_challenge: Option<&str>) -> String {
            match code_challenge {
                Some(c) => format!("https://provider.test/auth?state={state}&code_challenge={c}"),
                None => format!("https://provider.test/auth?state={state}"),
            }
        }
        async fn exchange_code(
            &self,
            _code: &str,
            _code_verifier: Option<&str>,
        ) -> Result<OAuthTokens, OAuthProviderError> {
            Err(OAuthProviderError::Http(400))
        }
        async fn fetch_profile(
            &self,
            _access_token: &str,
        ) -> Result<OAuthProfile, OAuthProviderError> {
            Err(OAuthProviderError::EmailNotVerified)
        }
    }

    #[tokio::test]
    async fn oauth_provider_is_object_safe() {
        // The provider must be storable as `Arc<dyn _>` and dispatch through the vtable.
        let provider: Arc<dyn OAuthProvider> = Arc::new(DummyProvider);
        assert_eq!(provider.name(), "dummy");
        assert!(provider.authorize_url("abc", None).contains("state=abc"));
        assert!(
            provider
                .authorize_url("abc", Some("chal"))
                .contains("code_challenge=chal")
        );
        assert!(matches!(
            provider.exchange_code("c", None).await,
            Err(OAuthProviderError::Http(400))
        ));
        assert!(matches!(
            provider.fetch_profile("t").await,
            Err(OAuthProviderError::EmailNotVerified)
        ));
    }

    #[test]
    fn registry_accumulates_providers() {
        // The registry newtype carries the provider list from config to the builder.
        let registry = OAuthProviders::new().with(Arc::new(DummyProvider));
        assert!(!registry.is_empty());
        assert_eq!(registry.0.len(), 1);
        assert!(OAuthProviders::default().is_empty());
    }

    #[test]
    fn oauth_tokens_debug_redacts_credential_fields() {
        // A `{:?}` of provider tokens must never expose the access/id/refresh tokens, while
        // the non-secret fields stay visible for observability.
        let tokens = OAuthTokens {
            access_token: "ya29.secret-access".to_owned(),
            token_type: "bearer".to_owned(),
            expires_in: Some(3600),
            scope: Some("openid email".to_owned()),
            id_token: Some("eyJ.secret-id".to_owned()),
            refresh_token: Some("1//secret-refresh".to_owned()),
        };
        let rendered = format!("{tokens:?}");
        assert!(!rendered.contains("ya29.secret-access"));
        assert!(!rendered.contains("eyJ.secret-id"));
        assert!(!rendered.contains("1//secret-refresh"));
        assert!(rendered.contains("[REDACTED]"));
        assert!(rendered.contains("bearer"));
        assert!(rendered.contains("3600"));
        // A token-less response renders `None`, not a redaction marker, for the optionals.
        let empty = OAuthTokens {
            access_token: String::new(),
            token_type: "bearer".to_owned(),
            expires_in: None,
            scope: None,
            id_token: None,
            refresh_token: None,
        };
        assert!(format!("{empty:?}").contains("id_token: None"));
    }

    #[test]
    fn provider_error_messages_are_stable() {
        // These strings feed `tracing`; pin them against accidental rewording.
        assert_eq!(
            OAuthProviderError::Http(503).to_string(),
            "oauth provider returned http status 503"
        );
        assert_eq!(
            OAuthProviderError::Transport("dns".into()).to_string(),
            "oauth provider transport error: dns"
        );
        assert_eq!(
            OAuthProviderError::UnexpectedTokenType("mac".into()).to_string(),
            "oauth provider returned unexpected token type: mac"
        );
        assert_eq!(
            OAuthProviderError::EmailNotVerified.to_string(),
            "oauth provider email is not verified"
        );
        assert_eq!(
            OAuthProviderError::Decode("bad json".into()).to_string(),
            "oauth provider response decode error: bad json"
        );
    }
}
