//! The Redis-store abstraction: the domain-level, intent-named store traits the engine
//! services depend on, keyed by [`SessionKind`] rather than low-level Redis verbs. The
//! canonical implementation lives in `bymax-auth-redis`; the seam exists so the backing
//! store is swappable and each trait can be exercised by an in-memory fake under test.
//!
//! The key prefixes, the stored JSON shapes, the `{namespace}:` prefixing, and the
//! atomic Lua scripts are implementation details owned by the store impl — they never
//! appear on these traits. Every fallible method returns [`AuthError`], the same error
//! the engine surfaces.

use async_trait::async_trait;
use bymax_auth_types::AuthError;
use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

/// Selects the identity domain a store operation targets, which in turn selects the Redis
/// prefix pair (`rt`/`prt`, `rp`/`prp`, `sess`/`psess`, `sd`/`psd`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum SessionKind {
    /// Dashboard/tenant sessions.
    Dashboard,
    /// Platform-admin sessions.
    Platform,
}

/// The purpose namespace an OTP record belongs to. Its [`OtpPurpose::as_str`] form is the
/// `{purpose}` segment of the Redis key, byte-identical to nest-auth.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum OtpPurpose {
    /// OTP-based password reset.
    PasswordReset,
    /// Email-verification OTP.
    EmailVerification,
}

impl OtpPurpose {
    /// The stable wire form used as the OTP key's purpose segment.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::PasswordReset => "password_reset",
            Self::EmailVerification => "email_verification",
        }
    }
}

/// The stored refresh-session record. Holds everything needed to reissue an access token
/// without a database hit. `tenant_id` is absent for platform sessions. JSON is camelCase
/// for byte-parity with nest-auth payloads already in Redis.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionRecord {
    /// The owning user id.
    pub user_id: String,
    /// The tenant scope; absent for platform sessions.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tenant_id: Option<String>,
    /// The user's role at session creation.
    pub role: String,
    /// Human-readable device/browser string.
    pub device: String,
    /// Originating IP (trusted-proxy resolved).
    pub ip: String,
    /// Session creation time.
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
}

/// One session's display detail, returned by [`SessionStore::list_sessions`]. The
/// `session_hash` is the `sess:`-set member (a SHA-256 hex of the refresh token), never
/// the raw token.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SessionDetail {
    /// The stored session hash (set member); a display id, never the raw token.
    pub session_hash: String,
    /// Human-readable device/browser string.
    pub device: String,
    /// Originating IP.
    pub ip: String,
    /// Session creation time.
    #[serde(with = "time::serde::rfc3339")]
    pub created_at: OffsetDateTime,
    /// Last observed activity time.
    #[serde(with = "time::serde::rfc3339")]
    pub last_activity_at: OffsetDateTime,
}

/// The parameters of an atomic refresh rotation, grouped so [`SessionStore::rotate`]
/// takes a single value instead of a long positional argument list. The new **raw** token
/// is generated by the caller; only its `new_hash` ever becomes a key — the raw value is
/// never written to the store. The `Debug` impl redacts `new_raw` so the live credential
/// cannot leak into a log.
#[derive(Clone)]
pub struct SessionRotation {
    /// Hash of the presented (old) refresh token.
    pub old_hash: String,
    /// Hash of the freshly-minted (new) refresh token.
    pub new_hash: String,
    /// The new raw refresh token (used by the caller, never persisted as a key).
    pub new_raw: String,
    /// The session record bound to the new token.
    pub new_record: SessionRecord,
    /// TTL for the new refresh session, in seconds.
    pub refresh_ttl: u64,
    /// TTL for the rotation grace pointer, in seconds.
    pub grace_ttl: u64,
}

impl std::fmt::Debug for SessionRotation {
    /// Redacts `new_raw` (the live refresh token); the hashes and record are display-safe.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SessionRotation")
            .field("old_hash", &self.old_hash)
            .field("new_hash", &self.new_hash)
            .field("new_raw", &"[REDACTED]")
            .field("new_record", &self.new_record)
            .field("refresh_ttl", &self.refresh_ttl)
            .field("grace_ttl", &self.grace_ttl)
            .finish()
    }
}

/// The outcome of an atomic refresh rotation (`refresh_rotate`).
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum RotateOutcome {
    /// The old token was present and consumed; the caller issues the new token bound to
    /// this record and updates the session bookkeeping.
    Rotated(SessionRecord),
    /// The old token was already rotated but is inside the grace window; the caller mints
    /// a fresh token for this recovered record without planting a new grace pointer.
    Grace(SessionRecord),
    /// Neither the live token nor a grace pointer was found — the refresh is invalid.
    Invalid,
}

/// A verified-claims snapshot minted into a single-use WebSocket upgrade ticket. The
/// value is a snapshot, never a token. JSON is camelCase.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WsTicketSnapshot {
    /// The subject (user id).
    pub sub: String,
    /// The tenant scope; absent for platform tickets.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    pub tenant_id: Option<String>,
    /// The user's role.
    pub role: String,
    /// The account status at mint time.
    pub status: String,
    /// Whether MFA is enabled on the account.
    pub mfa_enabled: bool,
    /// Whether the originating session had satisfied MFA.
    pub mfa_verified: bool,
}

/// Refresh-session lifecycle plus access-JWT revocation. Backs the `rt`/`prt`, `rp`/`prp`,
/// `sess`/`psess`, `sd`/`psd`, and `rv` keyspaces.
///
/// # Errors
///
/// Returns [`AuthError`] on a store failure; ownership-checked operations return the
/// matching typed variant (e.g. [`AuthError::SessionNotFound`] from
/// [`SessionStore::revoke_session`], [`AuthError::RefreshTokenInvalid`] surfaced by the
/// caller on [`RotateOutcome::Invalid`]).
#[async_trait]
pub trait SessionStore: Send + Sync {
    /// Persist a freshly-issued refresh session and register it in the user's session set.
    async fn create_session(
        &self,
        kind: SessionKind,
        token_hash: &str,
        detail: &SessionRecord,
        ttl_secs: u64,
    ) -> Result<(), AuthError>;

    /// Atomic rotation with a grace window, driven by a [`SessionRotation`] bundle.
    async fn rotate(
        &self,
        kind: SessionKind,
        rotation: &SessionRotation,
    ) -> Result<RotateOutcome, AuthError>;

    /// Look up a live session by refresh-token hash, without rotating it.
    async fn find_session(
        &self,
        kind: SessionKind,
        token_hash: &str,
    ) -> Result<Option<SessionRecord>, AuthError>;

    /// List all live sessions for a user.
    async fn list_sessions(
        &self,
        kind: SessionKind,
        user_id: &str,
    ) -> Result<Vec<SessionDetail>, AuthError>;

    /// Ownership-checked single revoke. Returns [`AuthError::SessionNotFound`] when the
    /// hash is not owned by the user.
    async fn revoke_session(
        &self,
        kind: SessionKind,
        user_id: &str,
        session_hash: &str,
    ) -> Result<(), AuthError>;

    /// Revoke every session for a user in one transaction.
    async fn revoke_all(&self, kind: SessionKind, user_id: &str) -> Result<(), AuthError>;

    /// Add a JTI (preferred) or full-JWT hash to the access-token blacklist for its
    /// remaining lifetime.
    async fn blacklist_access(
        &self,
        jti_or_hash: &str,
        remaining_ttl_secs: u64,
    ) -> Result<(), AuthError>;

    /// Whether an access JTI or JWT hash is blacklisted — consulted on every protected
    /// request.
    async fn is_blacklisted(&self, jti_or_hash: &str) -> Result<bool, AuthError>;
}

/// One-time-password records for email verification and OTP-based password reset.
///
/// # Errors
///
/// Returns [`AuthError`] on a store failure; [`OtpStore::verify`] returns the typed
/// outcome ([`AuthError::OtpExpired`], [`AuthError::OtpInvalid`],
/// [`AuthError::OtpMaxAttempts`], or `Ok(())` on success).
#[async_trait]
pub trait OtpStore: Send + Sync {
    /// Store an OTP code for a purpose+identifier with a TTL.
    async fn put(
        &self,
        purpose: OtpPurpose,
        identifier: &str,
        code: &str,
        ttl_secs: u64,
    ) -> Result<(), AuthError>;

    /// Atomically verify the code, bump the attempt counter, and consume on success.
    async fn verify(
        &self,
        purpose: OtpPurpose,
        identifier: &str,
        code: &str,
        max_attempts: u32,
    ) -> Result<(), AuthError>;

    /// Begin a resend if the cooldown has elapsed; `false` means a resend already
    /// happened inside the cooldown window.
    async fn try_begin_resend(
        &self,
        purpose: OtpPurpose,
        identifier: &str,
        cooldown_secs: u64,
    ) -> Result<bool, AuthError>;
}

/// Fixed-window failed-attempt counters keyed by an HMAC of `tenant:email`.
///
/// # Errors
///
/// Returns [`AuthError`] on a store failure.
#[async_trait]
pub trait BruteForceStore: Send + Sync {
    /// Whether the identifier has reached `max_attempts` within its window.
    async fn is_locked(&self, identifier: &str, max_attempts: u32) -> Result<bool, AuthError>;

    /// Atomically increment the failure counter (setting the window TTL only on the first
    /// failure) and return the new count.
    async fn record_failure(&self, identifier: &str, window_secs: u64) -> Result<i64, AuthError>;

    /// Reset the counter (on a successful authentication).
    async fn reset(&self, identifier: &str) -> Result<(), AuthError>;

    /// Seconds remaining on the current lockout window, or `0` when not locked.
    async fn remaining_lockout_secs(&self, identifier: &str) -> Result<u64, AuthError>;
}

/// The single-use WebSocket upgrade-ticket store. A ticket is minted from an
/// already-authorized, MFA-satisfied session and redeemed exactly once at the WS
/// handshake, so an access JWT never appears in a URL.
///
/// # Errors
///
/// Returns [`AuthError`] on a store failure.
#[async_trait]
pub trait WsTicketStore: Send + Sync {
    /// Mint a single-use ticket holding the verified-claims snapshot, returning the raw
    /// ticket the client presents at the handshake.
    async fn mint(&self, snapshot: &WsTicketSnapshot, ttl_secs: u64) -> Result<String, AuthError>;

    /// Redeem and consume a ticket (single-use), returning its snapshot or `None` when the
    /// ticket is unknown or already consumed.
    async fn redeem(&self, ticket: &str) -> Result<Option<WsTicketSnapshot>, AuthError>;
}

#[cfg(test)]
mod tests {
    use super::*;

    fn session_record() -> SessionRecord {
        SessionRecord {
            user_id: "u1".into(),
            tenant_id: Some("t1".into()),
            role: "MEMBER".into(),
            device: "Chrome on macOS".into(),
            ip: "203.0.113.4".into(),
            created_at: OffsetDateTime::UNIX_EPOCH,
        }
    }

    #[test]
    fn otp_purpose_wire_strings_are_stable() {
        // The purpose segment is part of the Redis key contract shared with nest-auth.
        assert_eq!(OtpPurpose::PasswordReset.as_str(), "password_reset");
        assert_eq!(OtpPurpose::EmailVerification.as_str(), "email_verification");
    }

    #[test]
    fn session_kind_variants_are_distinct() {
        // The kind selects the prefix pair; the two domains must never compare equal.
        assert_eq!(SessionKind::Dashboard, SessionKind::Dashboard);
        assert_ne!(SessionKind::Dashboard, SessionKind::Platform);
        assert_eq!(format!("{:?}", SessionKind::Platform), "Platform");
    }

    #[test]
    fn session_record_serializes_camel_case_and_omits_absent_tenant() -> serde_json::Result<()> {
        // Wire parity: fields are camelCase and a platform record (no tenant) omits the
        // `tenantId` key entirely rather than emitting null.
        let dashboard = session_record();
        let json = serde_json::to_string(&dashboard)?;
        assert!(json.contains("\"userId\":\"u1\""));
        assert!(json.contains("\"tenantId\":\"t1\""));
        assert!(json.contains("\"createdAt\":"));

        let platform = SessionRecord {
            tenant_id: None,
            ..session_record()
        };
        assert!(!serde_json::to_string(&platform)?.contains("tenantId"));

        // Round-trip parity.
        let back: SessionRecord = serde_json::from_str(&json)?;
        assert_eq!(back, dashboard);
        Ok(())
    }

    #[test]
    fn session_detail_round_trips() -> serde_json::Result<()> {
        // The detail record is read back from Redis on `list_sessions`; the serde shape
        // must round-trip every field.
        let detail = SessionDetail {
            session_hash: "abc123".into(),
            device: "Firefox".into(),
            ip: "198.51.100.7".into(),
            created_at: OffsetDateTime::UNIX_EPOCH,
            last_activity_at: OffsetDateTime::UNIX_EPOCH,
        };
        let json = serde_json::to_string(&detail)?;
        assert!(json.contains("\"sessionHash\":\"abc123\""));
        assert!(json.contains("\"lastActivityAt\":"));
        let back: SessionDetail = serde_json::from_str(&json)?;
        assert_eq!(back, detail);
        Ok(())
    }

    #[test]
    fn ws_ticket_snapshot_round_trips() -> serde_json::Result<()> {
        // The snapshot is the stored ticket value; camelCase + omit-absent-tenant parity.
        let snap = WsTicketSnapshot {
            sub: "u1".into(),
            tenant_id: Some("t1".into()),
            role: "MEMBER".into(),
            status: "ACTIVE".into(),
            mfa_enabled: true,
            mfa_verified: true,
        };
        let json = serde_json::to_string(&snap)?;
        assert!(json.contains("\"mfaEnabled\":true"));
        assert!(json.contains("\"mfaVerified\":true"));
        let back: WsTicketSnapshot = serde_json::from_str(&json)?;
        assert_eq!(back, snap);
        Ok(())
    }

    #[test]
    fn session_rotation_debug_redacts_the_raw_token() {
        // The raw refresh token must never appear in a `{:?}` of the rotation parameters.
        let rotation = SessionRotation {
            old_hash: "oldhash".to_owned(),
            new_hash: "newhash".to_owned(),
            new_raw: "live-refresh-token".to_owned(),
            new_record: session_record(),
            refresh_ttl: 60,
            grace_ttl: 30,
        };
        let rendered = format!("{rotation:?}");
        assert!(!rendered.contains("live-refresh-token"));
        assert!(rendered.contains("[REDACTED]"));
        assert!(rendered.contains("newhash"));
    }

    #[test]
    fn rotate_outcome_variants_carry_the_record() {
        // The three outcomes drive distinct caller behavior; pattern-matching each proves
        // the payloads are reachable.
        let record = session_record();
        assert!(matches!(
            RotateOutcome::Rotated(record.clone()),
            RotateOutcome::Rotated(_)
        ));
        assert!(matches!(
            RotateOutcome::Grace(record),
            RotateOutcome::Grace(_)
        ));
        assert!(matches!(RotateOutcome::Invalid, RotateOutcome::Invalid));
    }
}
