// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * [`AuthPlatformUser`] with every credential/secret field removed. Safe to serialize
 * and to return to callers. Produced via `SafeAuthPlatformUser::from(admin)`.
 */
export type AuthPlatformUserClient = { 
/**
 * Unique internal identifier.
 */
id: string, 
/**
 * Primary email.
 */
email: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Authorization role within the platform hierarchy.
 */
role: string, 
/**
 * Account lifecycle status.
 */
status: string, 
/**
 * Whether TOTP MFA is currently enabled.
 */
mfaEnabled: boolean, 
/**
 * Logical platform id, or `None` when single-platform.
 */
platformId?: string, 
/**
 * Most recent successful login, or `None` if never logged in.
 */
lastLoginAt: string | null, 
/**
 * Last modification time.
 */
updatedAt: string, 
/**
 * Record creation time.
 */
createdAt: string, };

/**
 * [`AuthUser`] with every credential/secret field removed. Safe to serialize and to
 * pass to consumer hooks. Produced via `SafeAuthUser::from(auth_user)`.
 *
 * This is the type handed to hooks, returned to callers, and serialized into API
 * responses — the Rust analogue of nest-auth's
 * `Omit<AuthUser, 'passwordHash' | 'mfaSecret' | 'mfaRecoveryCodes'>`.
 */
export type AuthUserClient = { 
/**
 * Unique internal identifier.
 */
id: string, 
/**
 * Primary email.
 */
email: string, 
/**
 * Display name.
 */
name: string, 
/**
 * Authorization role.
 */
role: string, 
/**
 * Account lifecycle status.
 */
status: string, 
/**
 * Tenant scope.
 */
tenantId: string, 
/**
 * Whether the email has been verified.
 */
emailVerified: boolean, 
/**
 * Whether TOTP MFA is currently enabled.
 */
mfaEnabled: boolean, 
/**
 * Primary OAuth provider id, or `None` for local-only accounts.
 */
oauthProvider?: string, 
/**
 * User's id within the OAuth provider, or `None` for local-only accounts.
 */
oauthProviderId?: string, 
/**
 * Most recent successful login, or `None` if never logged in.
 */
lastLoginAt: string | null, 
/**
 * Record creation time.
 */
createdAt: string, };
