// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthErrorCode } from "./error-codes";

/**
 * The reduced, client-parsed error shape exported for the typed client: the
 * authoritative `code` plus an advisory/localizable `message`. The full wire body is
 * [`AuthErrorEnvelope`]; this is the projection clients decode.
 */
export type AuthErrorResponse = { 
/**
 * The stable, authoritative `auth.*` code.
 */
code: AuthErrorCode, 
/**
 * The advisory English (or host-localized) message.
 */
message: string, };

/**
 * A single field-level validation failure, surfaced under `error.details` for the
 * adapter-originated [`AuthErrorCode::Validation`] code.
 */
export type FieldError = { 
/**
 * The offending request field (dotted path for nested fields).
 */
field: string, 
/**
 * Human-readable reason the field was rejected.
 */
message: string, };
