// GENERATED by bymax-auth-types ts-rs — do not edit by hand.

export const AUTH_ACCESS_COOKIE_NAME = "access_token";
export const AUTH_REFRESH_COOKIE_NAME = "refresh_token";
export const AUTH_HAS_SESSION_COOKIE_NAME = "has_session";
export const AUTH_HAS_SESSION_COOKIE_VALUE = "1";
export const AUTH_REFRESH_COOKIE_PATH = "/auth";
export const MFA_TEMP_COOKIE_NAME = "mfa_temp_token";
export const MFA_TEMP_COOKIE_MAX_AGE_SECONDS = 300;
