// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stable, serializable error code. Each variant serializes to its exact `auth.*`
 * string literal, byte-identical to nest-auth's `AUTH_ERROR_CODES`, and maps to a
 * fixed HTTP status via [`AuthErrorCode::http_status`].
 */
export type AuthErrorCode = "auth.invalid_credentials" | "auth.account_locked" | "auth.account_inactive" | "auth.account_suspended" | "auth.account_banned" | "auth.pending_approval" | "auth.token_expired" | "auth.token_revoked" | "auth.token_invalid" | "auth.refresh_token_invalid" | "auth.session_expired" | "auth.session_limit_reached" | "auth.session_not_found" | "auth.token_missing" | "auth.email_already_exists" | "auth.email_not_verified" | "auth.mfa_required" | "auth.mfa_invalid_code" | "auth.mfa_already_enabled" | "auth.mfa_not_enabled" | "auth.mfa_setup_required" | "auth.mfa_temp_token_invalid" | "auth.recovery_code_invalid" | "auth.password_too_weak" | "auth.password_reset_token_invalid" | "auth.password_reset_token_expired" | "auth.otp_invalid" | "auth.otp_expired" | "auth.otp_max_attempts" | "auth.insufficient_role" | "auth.forbidden" | "auth.invalid_invitation_token" | "auth.oauth_failed" | "auth.oauth_email_mismatch" | "auth.platform_auth_required" | "auth.validation" | "auth.too_many_requests" | "auth.internal";
export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: "auth.invalid_credentials",
  ACCOUNT_LOCKED: "auth.account_locked",
  ACCOUNT_INACTIVE: "auth.account_inactive",
  ACCOUNT_SUSPENDED: "auth.account_suspended",
  ACCOUNT_BANNED: "auth.account_banned",
  PENDING_APPROVAL: "auth.pending_approval",
  TOKEN_EXPIRED: "auth.token_expired",
  TOKEN_REVOKED: "auth.token_revoked",
  TOKEN_INVALID: "auth.token_invalid",
  REFRESH_TOKEN_INVALID: "auth.refresh_token_invalid",
  SESSION_EXPIRED: "auth.session_expired",
  SESSION_LIMIT_REACHED: "auth.session_limit_reached",
  SESSION_NOT_FOUND: "auth.session_not_found",
  TOKEN_MISSING: "auth.token_missing",
  EMAIL_ALREADY_EXISTS: "auth.email_already_exists",
  EMAIL_NOT_VERIFIED: "auth.email_not_verified",
  MFA_REQUIRED: "auth.mfa_required",
  MFA_INVALID_CODE: "auth.mfa_invalid_code",
  MFA_ALREADY_ENABLED: "auth.mfa_already_enabled",
  MFA_NOT_ENABLED: "auth.mfa_not_enabled",
  MFA_SETUP_REQUIRED: "auth.mfa_setup_required",
  MFA_TEMP_TOKEN_INVALID: "auth.mfa_temp_token_invalid",
  RECOVERY_CODE_INVALID: "auth.recovery_code_invalid",
  PASSWORD_TOO_WEAK: "auth.password_too_weak",
  PASSWORD_RESET_TOKEN_INVALID: "auth.password_reset_token_invalid",
  PASSWORD_RESET_TOKEN_EXPIRED: "auth.password_reset_token_expired",
  OTP_INVALID: "auth.otp_invalid",
  OTP_EXPIRED: "auth.otp_expired",
  OTP_MAX_ATTEMPTS: "auth.otp_max_attempts",
  INSUFFICIENT_ROLE: "auth.insufficient_role",
  FORBIDDEN: "auth.forbidden",
  INVALID_INVITATION_TOKEN: "auth.invalid_invitation_token",
  OAUTH_FAILED: "auth.oauth_failed",
  OAUTH_EMAIL_MISMATCH: "auth.oauth_email_mismatch",
  PLATFORM_AUTH_REQUIRED: "auth.platform_auth_required",
  VALIDATION: "auth.validation",
  TOO_MANY_REQUESTS: "auth.too_many_requests",
  INTERNAL: "auth.internal",
} as const;
