// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Access token for tenant/dashboard users. The TypeScript counterpart is
 * `DashboardJwtPayload`.
 */
export type DashboardJwtPayload = { 
/**
 * Subject — the user id.
 */
sub: string, 
/**
 * Token id (UUID v4) — the access-token blacklist key.
 */
jti: string, 
/**
 * Tenant scope.
 */
tenantId: string, 
/**
 * Authorization role.
 */
role: string, 
/**
 * Discriminator — always `"dashboard"`.
 */
type: DashboardType, 
/**
 * Account lifecycle status (e.g. "ACTIVE", "PENDING_APPROVAL").
 */
status: string, 
/**
 * Whether the account has MFA configured (drives the MFA-required guard).
 */
mfaEnabled: boolean, 
/**
 * Whether this session has cleared the second factor.
 */
mfaVerified: boolean, 
/**
 * Issued-at (seconds since the Unix epoch).
 */
iat: number, 
/**
 * Expiry (seconds since the Unix epoch).
 */
exp: number, 
/**
 * The user's token **epoch** at issuance — a per-user generation counter the server bumps
 * to invalidate every outstanding access token at once (a password reset or a full
 * sign-out-everywhere). Verification rejects the token when its epoch is below the user's
 * current stored epoch. Defaults to `0` on a legacy token that predates the field, which is
 * never rejected while the stored epoch is also `0` (the mechanism is inert until a bump).
 */
epoch: number, };

/**
 * Discriminator value for a dashboard access token. Serializes to `"dashboard"`.
 */
export type DashboardType = "dashboard";

/**
 * Which identity domain an MFA-temp token bridges — selects the repository and result
 * type downstream. Serializes to `"dashboard"` / `"platform"`.
 */
export type MfaContext = "dashboard" | "platform";

/**
 * Short-lived token bridging the password step and the MFA challenge. The TypeScript
 * counterpart is `MfaTempPayload`.
 */
export type MfaTempPayload = { 
/**
 * Subject — the user/admin id.
 */
sub: string, 
/**
 * Token id (UUID v4) — also written to the single-use MFA marker.
 */
jti: string, 
/**
 * Discriminator — always `"mfa_challenge"`.
 */
type: MfaTempType, 
/**
 * Which identity domain this challenge belongs to.
 */
context: MfaContext, 
/**
 * Issued-at (seconds since the Unix epoch).
 */
iat: number, 
/**
 * Expiry (seconds since the Unix epoch).
 */
exp: number, };

/**
 * Discriminator value for an MFA-temp token. Serializes to `"mfa_challenge"`.
 */
export type MfaTempType = "mfa_challenge";

/**
 * Access token for platform admins — no `tenantId`. The TypeScript counterpart is
 * `PlatformJwtPayload`.
 */
export type PlatformJwtPayload = { 
/**
 * Subject — the admin id.
 */
sub: string, 
/**
 * Token id (UUID v4) — the access-token blacklist key.
 */
jti: string, 
/**
 * Authorization role within the platform hierarchy.
 */
role: string, 
/**
 * Discriminator — always `"platform"`.
 */
type: PlatformType, 
/**
 * Whether the account has MFA configured.
 */
mfaEnabled: boolean, 
/**
 * Whether this session has cleared the second factor.
 */
mfaVerified: boolean, 
/**
 * Issued-at (seconds since the Unix epoch).
 */
iat: number, 
/**
 * Expiry (seconds since the Unix epoch).
 */
exp: number, 
/**
 * The admin's token **epoch** at issuance — the platform-domain analogue of
 * [`DashboardClaims::epoch`]: a per-admin generation counter the server bumps to invalidate
 * every outstanding platform access token at once. Defaults to `0` on a legacy token.
 */
epoch: number, };

/**
 * Discriminator value for a platform access token. Serializes to `"platform"`.
 */
export type PlatformType = "platform";
