// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Access token for tenant/dashboard users. The TypeScript counterpart is
 * `DashboardJwtPayload`.
 */
export type DashboardJwtPayload = { 
/**
 * Subject — the user id.
 */
sub: string, 
/**
 * Token id (UUID v4) — the access-token blacklist key.
 */
jti: string, 
/**
 * Tenant scope.
 */
tenantId: string, 
/**
 * Authorization role.
 */
role: string, 
/**
 * Discriminator — always `"dashboard"`.
 */
type: DashboardType, 
/**
 * Account lifecycle status (e.g. "ACTIVE", "PENDING_APPROVAL").
 */
status: string, 
/**
 * Whether the account has MFA configured (drives the MFA-required guard).
 */
mfaEnabled: boolean, 
/**
 * Whether this session has cleared the second factor.
 */
mfaVerified: boolean, 
/**
 * Issued-at (seconds since the Unix epoch).
 */
iat: number, 
/**
 * Expiry (seconds since the Unix epoch).
 */
exp: number, 
/**
 * The user's token **epoch** at issuance — a per-user generation counter the server bumps
 * to invalidate every outstanding access token at once (a password reset or a full
 * sign-out-everywhere). **Server-side** verification rejects the token when its epoch is
 * below the user's current stored epoch; the edge/WASM verifier carries this claim but does
 * not consult it (it checks signature, `iat`, and `exp` only), exactly like the jti
 * blacklist. Defaults to `0` when the claim is absent, which is never rejected while the
 * stored epoch is also `0` (the mechanism is inert until a bump) and always rejected once
 * it is bumped — the fail-closed direction.
 *
 * Exported as an optional TS property: the decode-only edge path passes the raw JWT payload
 * through untyped, so a token really can arrive without the key (serde's default only
 * applies when deserializing into this struct). Rendered via `Option::<f64>` because
 * ts-rs maps 64-bit integers to `bigint`, while `JSON.parse` yields a `number`.
 */
epoch?: number, 
/**
 * The `iss` claim, present only when the deployment configured `jwt.issuer`.
 *
 * Absent by default. When the verifier is configured with a value, a token carrying a
 * different one — or none at all — is rejected: accepting an unstamped token would give
 * an attacker a way to opt out of the check by omitting the claim.
 */
iss?: string, 
/**
 * The `aud` claim, with the same semantics as [`Self::iss`]. With HS256 the verifier can
 * also sign, so audience binding is what stops a token minted for one service being
 * replayed at another that trusts the same secret.
 */
aud?: string, };

/**
 * Discriminator value for a dashboard access token. Serializes to `"dashboard"`.
 */
export type DashboardType = "dashboard";

/**
 * Which identity domain an MFA-temp token bridges — selects the repository and result
 * type downstream. Serializes to `"dashboard"` / `"platform"`.
 */
export type MfaContext = "dashboard" | "platform";

/**
 * Short-lived token bridging the password step and the MFA challenge. The TypeScript
 * counterpart is `MfaTempPayload`.
 */
export type MfaTempPayload = { 
/**
 * Subject — the user/admin id.
 */
sub: string, 
/**
 * Token id (UUID v4) — also written to the single-use MFA marker.
 */
jti: string, 
/**
 * Discriminator — always `"mfa_challenge"`.
 */
type: MfaTempType, 
/**
 * Which identity domain this challenge belongs to.
 */
context: MfaContext, 
/**
 * The tenant the challenged account belongs to — present on the dashboard plane, absent
 * on the platform plane, whose admins are cross-tenant and carry none.
 *
 * Without it the challenge had no tenant in scope at all, and every decision it makes ran
 * on an account resolved by id alone: the user lookup passed `None`, so the status gate,
 * `mfa_enabled`, the encrypted secret and the recovery-code digests were all read from
 * whichever row the host returned, and the session was minted for that row. Under a host
 * schema that numbers users per tenant — which a library cannot rule out — every tenant
 * has a user `1`. It also left the pre-fetch challenge counter with nothing to scope by,
 * so failures from one tenant spent another tenant's lockout budget.
 *
 * Optional in the wire format so the claim is additive, but a dashboard challenge token
 * WITHOUT it is refused at verification rather than falling back to the unscoped shape —
 * a fallback would leave the vulnerable derivation reachable by simply omitting a field.
 */
tenantId?: string, 
/**
 * The subject's token **epoch** at issuance, in the plane named by [`Self::context`].
 *
 * The challenge token is a credential like any other — half of one, held by a caller who
 * has already proved the password — and it must die with the rest when the account's
 * credentials are rotated. Without this claim it did not: a password reset bumps the epoch
 * and kills every access token, but nothing touched an outstanding `mfa:` marker, so a
 * challenge token minted before the reset stayed redeemable for its whole TTL and
 * completing it issued a full session under the *new* epoch. The reset is meant to end
 * everything the old credential could still reach.
 *
 * Defaults to `0` when the claim is absent, so the mechanism stays inert until the first
 * bump — the same contract as [`DashboardClaims::epoch`].
 */
epoch?: number, 
/**
 * Issued-at (seconds since the Unix epoch).
 */
iat: number, 
/**
 * Expiry (seconds since the Unix epoch).
 */
exp: number, 
/**
 * The `iss` claim, present only when the deployment configured `jwt.issuer`.
 */
iss?: string, 
/**
 * The `aud` claim, with the same semantics as [`Self::iss`].
 */
aud?: string, };

/**
 * Discriminator value for an MFA-temp token. Serializes to `"mfa_challenge"`.
 */
export type MfaTempType = "mfa_challenge";

/**
 * Access token for platform admins — no `tenantId`. The TypeScript counterpart is
 * `PlatformJwtPayload`.
 */
export type PlatformJwtPayload = { 
/**
 * Subject — the admin id.
 */
sub: string, 
/**
 * Token id (UUID v4) — the access-token blacklist key.
 */
jti: string, 
/**
 * Authorization role within the platform hierarchy.
 */
role: string, 
/**
 * Discriminator — always `"platform"`.
 */
type: PlatformType, 
/**
 * Whether the account has MFA configured.
 */
mfaEnabled: boolean, 
/**
 * Whether this session has cleared the second factor.
 */
mfaVerified: boolean, 
/**
 * Issued-at (seconds since the Unix epoch).
 */
iat: number, 
/**
 * Expiry (seconds since the Unix epoch).
 */
exp: number, 
/**
 * The admin's token **epoch** at issuance — the platform-domain analogue of
 * [`DashboardClaims::epoch`]: a per-admin generation counter the server bumps to invalidate
 * every outstanding platform access token at once. Enforced by **server-side** verification
 * only; the edge/WASM verifier carries it without consulting it. Defaults to `0` when the
 * claim is absent, and is exported as an optional TS property for the same reason as
 * [`DashboardClaims::epoch`].
 */
epoch?: number, 
/**
 * The `iss` claim, present only when the deployment configured `jwt.issuer`.
 *
 * Absent by default. When the verifier is configured with a value, a token carrying a
 * different one — or none at all — is rejected: accepting an unstamped token would give
 * an attacker a way to opt out of the check by omitting the claim.
 */
iss?: string, 
/**
 * The `aud` claim, with the same semantics as [`Self::iss`]. With HS256 the verifier can
 * also sign, so audience binding is what stops a token minted for one service being
 * replayed at another that trusts the same secret.
 */
aud?: string, };

/**
 * Discriminator value for a platform access token. Serializes to `"platform"`.
 */
export type PlatformType = "platform";
